service: lambda-covid-19-lr-demo

custom:
  defaultProyecto: "Ejercicio implementacion de regresion lineal con datos covid"

  Proyecto: covid-19-lr-demo
  region: us-east-X
  stage: ${self:custom.currentStage}
  apiNamePrefix: ${self:custom.currentStage}

  defaultStage: dev
  currentStage: ${opt:stage, self:custom.defaultStage} # 'dev' is default unless overriden by --stage flag

provider:
  name: aws
  runtime: python3.6
  apiKeys:
    - api-key-covid19
  stackTags:
    Proyecto: ${self:custom.Proyecto}
  region: ${self:custom.region}

functions:
  covid19lr:
    handler: lambda_function.lambda_handler
    timeout: 30
    events:
      - http:
          path: covid-19-lr-demo
          method: post
          private: true